-- External table for staging CSV data from BI Publisher
CREATE TABLE FA_TRANSACTIONS_EXT (
  TRANSACTION_HEADER_ID     NUMBER,
  TRANSACTION_TYPE_CODE     VARCHAR2(30),
  TRX_DATE                  DATE,
  ASSET_ID                  NUMBER,
  ASSET_NUMBER              VARCHAR2(30),
  BOOK_TYPE_CODE            VARCHAR2(30),
  CATEGORY_ID               NUMBER,
  COST_DELTA                NUMBER,
  DEPRN_RESERVE_DELTA       NUMBER,
  PROCEEDS                  NUMBER,
  GAIN_LOSS                 NUMBER,
  UNITS_DELTA               NUMBER,
  CODE_COMBINATION_ID       NUMBER
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY DATA_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    MISSING FIELD VALUES ARE NULL
  )
  LOCATION ('fa_transactions_*.csv')
);
