let
  Source = Csv.Document(
    File.Contents("data/ap_aging_schedule_*.csv"),
    [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
  ),
  Promote = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  Types = Table.TransformColumnTypes(
    Promote,
    {
      {"AS_OF_DATE", type date},
      {"SCHEDULE_KEY", type text},
      {"INVOICE_ID", Int64.Type},
      {"PAYMENT_NUM", Int64.Type},
      {"ORG_ID", Int64.Type},
      {"VENDOR_ID", Int64.Type},
      {"VENDOR_SITE_ID", Int64.Type},
      {"INVOICE_NUM", type text},
      {"INVOICE_DATE", type date},
      {"INVOICE_RECEIVED_DATE", type date},
      {"DUE_DATE", type date},
      {"TERMS_ID", Int64.Type},
      {"TERMS_DATE", type date},
      {"INVOICE_TYPE_LOOKUP_CODE", type text},
      {"INVOICE_CURRENCY_CODE", type text},
      {"PAYMENT_CURRENCY_CODE", type text},
      {"PAYMENT_METHOD_CODE", type text},
      {"PAYMENT_METHOD_LOOKUP_CODE", type text},
      {"PAY_GROUP_LOOKUP_CODE", type text},
      {"SOURCE", type text},
      {"PO_HEADER_ID", Int64.Type},
      {"PAYMENT_STATUS_FLAG_SCHEDULE", type text},
      {"PAYMENT_STATUS_FLAG_INVOICE", type text},
      {"HOLD_FLAG", type text},
      {"HELD_BY", Int64.Type},
      {"HOLD_DATE", type date},
      {"IBY_HOLD_REASON", type text},
      {"GROSS_AMOUNT", type number},
      {"AMOUNT_REMAINING", type number},
      {"OPEN_AMOUNT", type number},
      {"INVOICE_AMOUNT", type number},
      {"AMOUNT_PAID", type number},
      {"PAYMENT_AMOUNT_TOTAL", type number},
      {"DAYS_PAST_DUE", Int64.Type},
      {"AGING_BUCKET", type text},
      {"AGING_DIRECTION", type text},
      {"IS_CURRENT", Int64.Type},
      {"IS_PAST_DUE", Int64.Type},
      {"IS_DUE_NEXT_7_DAYS", Int64.Type},
      {"IS_DUE_NEXT_30_DAYS", Int64.Type},
      {"IS_CREDIT_MEMO", Int64.Type},
      {"IS_DEBIT_MEMO", Int64.Type},
      {"IS_PREPAYMENT", Int64.Type},
      {"IS_CANCELLED", Int64.Type},
      {"IS_ON_HOLD", Int64.Type},
      {"IS_FULLY_PAID", Int64.Type},
      {"IS_UNPAID", Int64.Type},
      {"IS_PARTIALLY_PAID", Int64.Type},
      {"HAS_PROJECT_DISTRIBUTION", Int64.Type},
      {"HAS_CAPITAL_PROJECT_DISTRIBUTION", Int64.Type},
      {"HAS_PO_MATCHED_DISTRIBUTION", Int64.Type},
      {"HAS_UNACCOUNTED_DISTRIBUTION", Int64.Type},
      {"HAS_ASSET_RELATED_DISTRIBUTION", Int64.Type},
      {"HAS_REVERSAL_DISTRIBUTION", Int64.Type},
      {"DISTRIBUTION_COUNT", Int64.Type},
      {"DISTRIBUTION_TOTAL_AMOUNT", type number},
      {"PROJECT_COUNT", Int64.Type},
      {"PO_DISTRIBUTION_COUNT", Int64.Type}
    }
  )
in
  Types
