-- Staging: AP invoice headers (one row per INVOICE_ID)
-- Source: AP_INVOICES_ALL (Oracle Fusion 26B)

WITH invoices AS (
    SELECT
        ai.invoice_id,
        ai.vendor_id,
        ai.vendor_site_id,
        ai.invoice_num,
        ai.invoice_date,
        ai.invoice_received_date,
        ai.goods_received_date,
        ai.invoice_type_lookup_code,
        ai.invoice_amount,
        ai.amount_paid,
        ai.payment_amount_total,
        ai.discount_amount_taken,
        ai.invoice_currency_code,
        ai.payment_currency_code,
        ai.payment_status_flag,
        ai.terms_id,
        ai.terms_date,
        ai.source,
        ai.description,
        ai.set_of_books_id,
        ai.org_id,
        ai.po_header_id,
        ai.accts_pay_code_combination_id,
        ai.pay_group_lookup_code,
        ai.payment_method_lookup_code,
        ai.approval_status,
        ai.cancelled_date,
        ai.cancelled_amount,
        ai.project_id,
        ai.task_id,
        ai.expenditure_type,
        ai.expenditure_item_date,
        ai.expenditure_organization_id,
        ai.pa_default_dist_ccid,
        CASE WHEN UPPER(ai.invoice_type_lookup_code) LIKE '%CREDIT%' THEN 1 ELSE 0 END AS is_credit_memo,
        CASE WHEN UPPER(ai.invoice_type_lookup_code) LIKE '%DEBIT%' THEN 1 ELSE 0 END AS is_debit_memo,
        CASE WHEN UPPER(ai.invoice_type_lookup_code) LIKE '%PREPAY%' THEN 1 ELSE 0 END AS is_prepayment,
        CASE WHEN ai.cancelled_date IS NOT NULL THEN 1 ELSE 0 END AS is_cancelled,
        ai.invoice_amount - COALESCE(ai.amount_paid, 0) AS invoice_open_amount_check
    FROM ap_invoices_all ai
)

SELECT
    invoice_id,
    vendor_id,
    vendor_site_id,
    invoice_num,
    invoice_date,
    invoice_received_date,
    goods_received_date,
    invoice_type_lookup_code,
    invoice_amount,
    amount_paid,
    payment_amount_total,
    discount_amount_taken,
    invoice_currency_code,
    payment_currency_code,
    payment_status_flag,
    terms_id,
    terms_date,
    source,
    description,
    set_of_books_id,
    org_id,
    po_header_id,
    accts_pay_code_combination_id,
    pay_group_lookup_code,
    payment_method_lookup_code,
    approval_status,
    cancelled_date,
    cancelled_amount,
    project_id,
    task_id,
    expenditure_type,
    expenditure_item_date,
    expenditure_organization_id,
    pa_default_dist_ccid,
    is_credit_memo,
    is_debit_memo,
    is_prepayment,
    is_cancelled,
    invoice_open_amount_check
FROM invoices
