-- Staging: AP payment schedules (one row per INVOICE_ID + PAYMENT_NUM)
-- Source: AP_PAYMENT_SCHEDULES_ALL (Oracle Fusion 26B)

WITH payment_schedules AS (
    SELECT
        ps.invoice_id,
        ps.payment_num,
        ps.org_id,
        ps.due_date,
        ps.gross_amount,
        ps.amount_remaining,
        ps.inv_curr_gross_amount,
        ps.payment_status_flag,
        ps.hold_flag,
        ps.held_by,
        ps.hold_date,
        ps.iby_hold_reason,
        ps.payment_method_lookup_code,
        ps.payment_method_code,
        ps.payment_priority,
        ps.discount_date,
        ps.discount_amount_available,
        ps.discount_amount_remaining,
        ps.checkrun_id,
        ps.creation_date,
        ps.created_by,
        ps.last_update_date,
        ps.last_updated_by,
        ps.remit_to_supplier_id,
        ps.remit_to_supplier_name,
        ps.remit_to_address_id,
        ps.remit_to_address_name,
        CAST(ps.invoice_id AS VARCHAR2(40)) || '-' || CAST(ps.payment_num AS VARCHAR2(20)) AS schedule_key,
        CASE WHEN ps.payment_status_flag = 'Y' THEN 1 ELSE 0 END AS is_paid,
        CASE WHEN ps.payment_status_flag = 'N' THEN 1 ELSE 0 END AS is_unpaid,
        CASE WHEN ps.payment_status_flag = 'P' THEN 1 ELSE 0 END AS is_partially_paid,
        CASE WHEN ps.hold_flag = 'Y' THEN 1 ELSE 0 END AS is_on_hold,
        ps.amount_remaining AS open_amount,
        ps.gross_amount AS schedule_gross_amount
    FROM ap_payment_schedules_all ps
)

SELECT
    invoice_id,
    payment_num,
    org_id,
    due_date,
    gross_amount,
    amount_remaining,
    inv_curr_gross_amount,
    payment_status_flag,
    hold_flag,
    held_by,
    hold_date,
    iby_hold_reason,
    payment_method_lookup_code,
    payment_method_code,
    payment_priority,
    discount_date,
    discount_amount_available,
    discount_amount_remaining,
    checkrun_id,
    creation_date,
    created_by,
    last_update_date,
    last_updated_by,
    remit_to_supplier_id,
    remit_to_supplier_name,
    remit_to_address_id,
    remit_to_address_name,
    schedule_key,
    is_paid,
    is_unpaid,
    is_partially_paid,
    is_on_hold,
    open_amount,
    schedule_gross_amount
FROM payment_schedules
